### ISSUE TITLE
Exception on IntelliJ15

### ISSUE THREAD

**Issue by gousiosg** [TestRoots/watchdog#217]
I 've just installed Watchdog on IntelliJ15 and opened a Scala project with it. Got the following error. This persists after a restart and the event log displays this: 

`09:59:58 AbstractMethodError: nl.tudelft.watchdog.intellij.logic.ui.listeners.IntelliJActivationListener.delayedApplicationDeactivated(Lcom/intellij/openapi/wm/IdeFrame;)V
`

every 10 seconds.

```
nl.tudelft.watchdog.intellij.logic.ui.listeners.IntelliJActivationListener.delayedApplicationDeactivated(Lcom/intellij/openapi/wm/IdeFrame;)V
java.lang.AbstractMethodError: nl.tudelft.watchdog.intellij.logic.ui.listeners.IntelliJActivationListener.delayedApplicationDeactivated(Lcom/intellij/openapi/wm/IdeFrame;)V
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:334)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
	at com.sun.proxy.$Proxy46.delayedApplicationDeactivated(Unknown Source)
	at com.intellij.ide.ApplicationActivationStateManager$1.actionPerformed(ApplicationActivationStateManager.java:114)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by levaja** [comment]
This is due to the change in API. This is resolved in WD 1.6.0.
