### ISSUE TITLE
[Eclipse] WatchDog crashes when CheckStyle is not loaded

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#325]
Stacktrace

```
java.lang.NoClassDefFoundError: nl/tudelft/watchdog/core/logic/ui/listeners/staticanalysis/CheckStyleChecksMessagesFetcher
	at nl.tudelft.watchdog.eclipse.logic.ui.listeners.staticanalysis.EclipseMarkupModelListener.<clinit>(EclipseMarkupModelListener.java:38)
	at nl.tudelft.watchdog.eclipse.logic.ui.listeners.WorkbenchListener.addStaticAnalysisListeners(WorkbenchListener.java:79)
	at nl.tudelft.watchdog.eclipse.logic.ui.listeners.WorkbenchListener.attachListeners(WorkbenchListener.java:62)
	at nl.tudelft.watchdog.eclipse.logic.InitializationManager.<init>(InitializationManager.java:75)
	at nl.tudelft.watchdog.eclipse.logic.InitializationManager.getInstance(InitializationManager.java:84)
	at nl.tudelft.watchdog.eclipse.ui.handlers.StartupHandler.startWatchDog(StartupHandler.java:41)
	at nl.tudelft.watchdog.eclipse.ui.handlers.StartupUIThread.checkWhetherToStartWatchDog(StartupUIThread.java:168)
	at nl.tudelft.watchdog.eclipse.ui.handlers.StartupUIThread.run(StartupUIThread.java:60)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4577)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4186)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.ClassNotFoundException: nl.tudelft.watchdog.core.logic.ui.listeners.staticanalysis.CheckStyleChecksMessagesFetcher cannot be found by nl.tudelft.WatchDog_3.1.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
```

cc @TimvdLippe

**Comment by TimvdLippe** [comment]
Does https://github.com/TestRoots/watchdog/blob/9e06ea0618c675bffd7a5dd86d130f63ab74c90d/eclipse/plugin/src/nl/tudelft/watchdog/eclipse/logic/ui/listeners/staticanalysis/EclipseMarkupModelListener.java#L41-L43 need to be throwable?
